version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "0.0.0.0:6969:6969"
  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:80:80"
   
    depends_on:
      - backend
