version: '4'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "0.0.0.0:6969:6969"
    depends_on:
      - model-service
      - data-generator
    environment:
      - MODEL_SERVICE_URL=http://model-service:8000
      - DATA_GENERATOR_URL=http://data-generator:8001

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend

  model-service:
    build:
      context: ./model
      dockerfile: Dockerfile
    volumes:
      - ./model:/app
    expose:
      - "8000"

  data-generator:
    build:
      context: ./data_generator
      dockerfile: Dockerfile
    volumes:
      - ./data_generator:/app
    expose:
      - "8001"