version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "6969:6969"
    environment:
      - TZ=Europe/Berlin
  frontend:
    build: ./frontend
    ports:
      - "80:80"
   
    depends_on:
      - backend
