# Use Python base image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Install required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8001

# Start FastAPI with uvicorn
CMD ["uvicorn", "data_generator:app", "--host", "0.0.0.0", "--port", "8001"]
